### ISSUE TITLE
Error with v2.2.0 build

### ISSUE THREAD

**Issue by BrayanDSO** [ByteHamster/SearchPreference#22]
Apparently there is an error with v2.2.0 build on [jitpack](https://jitpack.io/#ByteHamster/SearchPreference), which means I can't add it on my `build.gradle` file

Here's the log https://jitpack.io/com/github/ByteHamster/SearchPreference/v2.2.0/build.log

As I don't know if there is something I can do to help, I'm creating the issue.

**Comment by ByteHamster** [comment]
Fixed by @ov3rk1ll in #23
