### ISSUE TITLE
Improve the search history

### ISSUE THREAD

**Issue by BrayanDSO** [ByteHamster/SearchPreference#25]
Currently I'm avoiding to use the search history option on AnkiDroid because the saved history tends to have only insipid results. 

Just as an example, taken on AntennaPod actually (I use it too, quite great app, thank you), instead of saving the last clicked items, i.e. `Select themes` and `App notifications`, it just saves `s` and `a`, which IMHO doesn't help much.

https://user-images.githubusercontent.com/69634269/184858505-0d092ae7-9824-4a44-8b1b-b45e2d3877e6.mp4

If it saved the last opened results with their full names it would be more useful IMO

I'd be willing to do a PR for it, and possibly make it the default history behavior (open to discussion), if that's fine with you.

**Comment by ByteHamster** [comment]
What happens when that setting is then later removed from the index or a user changes their language? I guess simply keeping it in the history as a string with the title (so basically ignoring the edge case) is the easiest approach.

**Comment by ByteHamster** [comment]
Ah, sorry. I did not want to close this. I was just wondering how to best store the selected entry. My suggestion basically was to store the title as text, and not use a more complex system that stores key and resource string for dynamic hiding/translation. Could lead to unexpected behavior, though, when users change the system language and then tapping the history entries no longer gives any search results.

**Comment by BrayanDSO** [comment]
Oh, I've misunderstood that, sorry.

> My suggestion basically was to store the title as text

Yeah, I agree. And that's what happens on my Samsung phone settings too. If I change the language, the history results are kept the way I searched them originally, i.e. on the language I searched it

**Comment by mikehardy** [comment]
Hey @ByteHamster ! Over at AnkiDroid our users have generously donated voluntarily to the developers and we have set up a process where people that have contributed to AnkiDroid may claim a share if they like. It is like the internet buying you a cup of coffee or a meal for helping AnkiDroid out :-). If that's of interest to you at all, head over to this document and you can read up on it then head over to OpenCollective and make an invoice as this link says - https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

Either way, thanks again for helping AnkiDroid :-). Cheers

**Comment by ByteHamster** [comment]
Thanks for the offer. I'm happy to help AnkiDroid - I don't need any compensation for that :)
