### ISSUE TITLE
Configurable shared preferences file

### ISSUE THREAD

**Issue by joserebelo** [ByteHamster/SearchPreference#28]
Hi,

I was looking into integrating this lib into [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge). However, we have different preference screens per device, with completely unrelated preferences / histories.

It would be nice to be able to configure a separate history per screen.

Looking at the code, it should be as simple as adding a configurable identifier for the history key (or a configurable shared prefs file) - not sure which one would be preferable. I'd be willing to open a PR with the changes, if this is something that would be desirable.

**Comment by ByteHamster** [comment]
Sounds good to me, if the default behavior is to keep the current history
