### ISSUE TITLE
Delete individual search history

### ISSUE THREAD

**Issue by SanjaySargam** [ByteHamster/SearchPreference#31]
**Is your feature request related to a problem? Please describe.**
Currently, we can delete all search history at once. There is no option to delete a particular search history individually

**Describe the solution you'd like**
Show a dialog box on clicking on a particular search history where user can delete it individually

**Screenshot**
![WhatsApp Image 2023-12-15 at 5 53 37 PM](https://github.com/ByteHamster/SearchPreference/assets/65113071/122b8f6d-9911-4d62-a135-07441d423b5d)

**Comment by ByteHamster** [comment]
Hmm, this feels a bit like an overkill. I want to keep this library simple and focused on a single job. The search functions on Google Play and in the settings app, for example, also don't have this. A search history is not something you want to micro-manage

**Comment by SanjaySargam** [comment]
I understand but Youtube and Google Chrome provide this feature. 
We used this library in AnkiDroid. We need such feature
https://github.com/ankidroid/Anki-Android/issues/14988

**Comment by ByteHamster** [comment]
As discussed over at https://github.com/ankidroid/Anki-Android/issues/14988, I don't really see a use-case for this other than "because we can". Sorry, I don't think we should add this to keep the library focused on the main task.
