### ISSUE TITLE
[BUG] `app:textClearHistory` has no effect

### ISSUE THREAD

**Issue by david-allison** [ByteHamster/SearchPreference#33]
Repro case:

```patch
Index: app/src/main/res/xml/preferences.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/res/xml/preferences.xml b/app/src/main/res/xml/preferences.xml
--- a/app/src/main/res/xml/preferences.xml	(revision 856ae2ca7f5a955dfb0eb7834319d159c269fba0)
+++ b/app/src/main/res/xml/preferences.xml	(date 1707366854942)
@@ -1,7 +1,9 @@
 <?xml version="1.0" encoding="utf-8"?>
-<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">
+<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto">
 
     <com.bytehamster.lib.preferencesearch.SearchPreference
+            app:textClearHistory="AA"
             android:key="searchPreference" />
 
     <CheckBoxPreference
```

**Comment by ByteHamster** [comment]
Do we actually need this attribute? I mean, shouldn't overwriting the resources already be enough to be fully translatable?

**Comment by david-allison** [comment]
attribute? No. Only that it's a breaking API change

`searchConfiguration.setTextClearHistory()` is also broken [also fixed in the PR], and it is useful to have a means to provide a `String` rather than override the resource:

* AnkiDroid currently uses a mix of `R.string` and [Pontoon](https://github.com/mozilla/pontoon) as sources for strings. It would be ideal to keep a potential migration to Pontoon on the table
  *  We don't want to waste `apk` space duplicating strings from a binary dependency into the XML
* One-time issue: Due to our translation syncing process, redefining the strings for testing is easier
  * Our codebase is only responsible for `/values`, not `/values-en`. Since `/values-en` in this repository takes priority over `/values`, testing changes didn't appear
* One-time issue:
  * We (incorrectly) redefined `no_results`. Until we fix this, it's cleaner to have this in the XML, rather than the code
